### ISSUE TITLE
No Strikethrough

### ISSUE THREAD

**Issue by amrrs** [dashokkumar93/To-Do-List#1]
Once the checkbox is checked, there doesn't seem to be an intuitive indication of completed tasks.

**Comment by dashokkumar93** [comment]
Will make those changes in the soon.

**Comment by dashokkumar93** [comment]
Made those changes. @amrrs . If you think of any further improvements in the app please let me know.

**Comment by amrrs** [comment]
Thanks @dashokkumar93 Looks good now.
